move CI further along
carygravel/graphics-tiff pull request #2
Opened 2021-05-07 03:07 UTC by PhilterPaper

Fix $to_write error, clean up so CI works (just Ubuntu -- you took out Windows?). Perl 5.26 and 5.32 appear to build and install correctly, but 5.22 still chokes on $(INST_DYNAMIC_LIB) not defined (bad Makefile). Someone is calling static_lib() in Depends.pm, which outputs the undefined INST_DYNAMIC_LIB. I suspect it has something to do with using dmake instead of gmake, but haven't yet found who calls static_lib(). The Depends.pm POD mentions explicitly calling method get_makefile_vars() from Makefile.PL, but that would be a major restructuring of the Makefile.PL.

2021-05-07 07:31 UTC, carygravel requested changes
Thanks for the fix. The extra semicolon is unnecessary. Would you mind removing it?

2021-05-07 07:32 UTC, carygravel reviewed
Which linter is complaining about the leading underscore? This is standard in XS.

2021-05-07 07:33 UTC, carygravel requested changes
Please merge this into the previous commit.

2021-05-07 12:45 UTC, PhilterPaper commented
OK, semi removed. If that's your preferred style (use ; as separator rather than a statement end), no problem. The Ubuntu linter you specified in the workflow refused to pass tiffperl.h until the underscore was removed, and the comment format changed. You'd think they'd be the same settings, but maybe you have something overriding the default settings for your account?

Is there anything else I need to do to get this merged? I don't understand your request to 'merge this into the previous commit'.

2021-05-08 07:28 UTC, carygravel commented
The linter works fine [in my workflow](https://github.com/carygravel/graphics-tiff/runs/2487098598?check_suite_focus=true). I guess some user config must play a part here, too.

2021-05-08 07:51 UTC, carygravel commented
The linter problem must be something that just got added, because now [I see it, too](https://github.com/carygravel/graphics-tiff/runs/2533503672?check_suite_focus=true). However, they are using a C++ linter on C/XS code. Thanks for the heads up. I'll try and understand why the linter is flagging it.

2021-05-13 14:25 UTC, PhilterPaper commented
When I took the ; out of Makefile.PL (I think that was the only change I made), suddenly the entire CI build/test fell over dead. (Linter claims to run OK.) TIFF.so isn't being built, and all tests fail. I don't know if this is the same problem that you're looking at. I haven't tried putting the ; back in and pushing it again. CI isn't reporting back _why_ the build appears to have failed.

BTW, I seem to recall seeing a GT install error go by. t/90-* complained about no 'egrep' available. Neither grep nor egrep come with Windows (`findstr` is similar), but grep _might_ be available on Strawberry's Linux-style build platform (mingw or something). Is `grep -E` the same as `egrep`? Just a 'heads up' on this possible problem.

2021-05-14 06:40 UTC, carygravel commented
> BTW, I seem to recall seeing a GT install error go by. t/90-* complained about no 'egrep' available. Neither grep nor egrep come with Windows (`findstr` is similar), but grep _might_ be available on Strawberry's Linux-style build platform (mingw or something). Is `grep -E` the same as `egrep`? Just a 'heads up' on this possible problem.

Yes `grep -E` is the same as `egrep`. Thanks for the heads up.

I'll fix the GT Windows build as soon as I get Alien::libtiff building.

If you can help me get Alien::libtiff building in Windows, I'd be very grateful. At the moment, it [builds in the Linux CI runner](https://github.com/carygravel/Perl-Alien-libtiff/runs/2533420041?check_suite_focus=true), but [not yet in Windows](https://github.com/carygravel/Perl-Alien-libtiff/runs/2533420061?check_suite_focus=true).

2021-05-14 13:30 UTC, carygravel commented
Thanks to some more help from one of the developers of Alien, [Alien::libtiff now builds in a Windows CI](https://github.com/carygravel/Perl-Alien-libtiff/runs/2583848040?check_suite_focus=true). I'll do some tidying up and then add Alien::libtiff as a prereq for GT on Windows (only). Unfortunately, it takes 20 minutes to build Alien::MSYS, necessary with Windows.

2021-05-20 08:58 UTC, carygravel commented
You are absolutely right. Merged.

2021-05-20 08:58 UTC, closed without merging